### ISSUE TITLE
Designers section not hiding and showing on click

### ISSUE THREAD

**Issue by sumitramanga** [QuentinMcCarthy/ocular-web-app-portfolio#2]
The designers section is not hiding nor showing on click of the view stats button. Refer to designers.js on line 154 and line 159 on my branch. Looking in the inspector the stats section is rendered inside of the designers sections

**Comment by sumitramanga** [comment]
A work around has been found. Instead of hiding the entire designers.js that is rendered in the DOM, the designer-profile div is being hidden so Stats only shows.

**Comment by QuentinMcCarthy** [comment]
A proper solution would be to move the Stats class out of the designers.js file and into the index.js file, that was you can hide the entire Designers page rather than only the profile div.
