### ISSUE TITLE
.projectWrapper class styles not being set

### ISSUE THREAD

**Issue by QuentinMcCarthy** [QuentinMcCarthy/ocular-web-app-portfolio#3]
.projectWrapper styles are not being set on the .projectWrapper elements. The elements are being created in a map loop, which could possibly be the reason, but I'm not sure.

**Comment by sumitramanga** [comment]
style is spelt wrong on line 172 ("stlye={bgImage}" instead of "style={bgImage}"). Maybe that's causing the problem?

**Comment by QuentinMcCarthy** [comment]
That solves the issue of the background image not being set. However, I don't believe that would be the cause of the problem.

Edit:
Apparently it might have been the cause, as it suddenly works.
